[package]
name = "bcommit"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
dirs = "7.0.0"
inquire = { version = "0.9.4", features = ["editor"] }
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"